### ISSUE TITLE
jenkins取消任务问题

### ISSUE THREAD

**Issue by liuzhognxiu** [Eerrly/JenkinsUnityPyAutoMator#1]
在使用了shell step构建之后，取消任务，python任务不会被立即中断，导致Unity工程没有执行中断的情况，请问有什么好的解决方法吗？目前使用signal库来监听

**Comment by liuzhognxiu** [comment]
补充：目前shell是通过异步执行shell的，单个任务执行三个不同平台的Unity任务。

**Comment by Eerrly** [comment]
如果你是使用的本项目代码，根据我以往的Unity构建操作，在Jenkins任务取消时，会中断掉python进程，从而也会让unity进程中断，并不会出现你所说的unity工程在执行过程中无法中断的清空。

**Comment by Eerrly** [comment]
如果你是使用的本项目代码，根据我以往的Unity构建操作，在Jenkins任务取消时，会中断掉python进程，从而也会让unity进程中断，并不会出现你所说的unity工程在执行过程中无法中断的情况。
